//
//  MessageGroup.swift
//  MessagingApp
//
//  Created by Jay Muthialu on 1/17/21.
//

import Foundation
import FirebaseFirestore

protocol FirebaseRepresentation {
    var toFireBaseModel: [String: Any] { get }
}


class MessageGroup {
    
    // Id will be generated by Firebased when saved
    var id: String? // This is Firebase ID
    var name = ""
    
    init(name: String?) {
        self.name = name ?? "No Name"
    }
    
    // Create object from document from Firebase
    init(document: QueryDocumentSnapshot) {
        let data = document.data()
        guard let name = data["name"] as? String else {
            return
        }
        self.name = name
        self.id = document.documentID
    }
    
}

extension MessageGroup: FirebaseRepresentation {
    
    var toFireBaseModel: [String : Any] {
        var json = [String: Any]()
        json["name"] = self.name
        if let id = self.id {
            json["id"] = id
        }
        return json
    }
    
}

extension MessageGroup: Comparable {
    
    static func == (lhs: MessageGroup, rhs: MessageGroup) -> Bool {
        return lhs.id == rhs.id
    }
    
    static func < (lhs: MessageGroup, rhs: MessageGroup) -> Bool {
        return lhs.name < rhs.name
    }
    
}

